/**
 * Account types and data structures for neowallet
 */

/**
 * Encrypted account data stored in the accounts file
 */
export interface EncryptedAccount {
  id: string; // Unique identifier for the account
  name: string; // User-friendly name
  address: string; // Public address (0x...)
  source: AccountSource; // Where the account came from
  encryptedPrivateKey?: string; // AES-encrypted private key (only for imported/generated accounts)
  createdAt: number; // Unix timestamp
  updatedAt: number; // Unix timestamp
}

/**
 * Decrypted account in memory (after unlock)
 */
export interface DecryptedAccount {
  id: string;
  name: string;
  address: string;
  source: AccountSource; // Where the account came from
  privateKey?: `0x${string}`; // Decrypted private key (only for imported/generated accounts)
  createdAt: number;
  updatedAt: number;
}

/**
 * Accounts file structure (stored on disk)
 */
export interface AccountsFile {
  version: number; // Schema version for future migrations
  accounts: EncryptedAccount[];
}

/**
 * Account source type
 */
export enum AccountSource {
  IMPORTED = "imported", // Imported from private key
  GENERATED = "generated", // Generated by the wallet
  FRAME = "frame", // Connected via Frame wallet
}

/**
 * Account creation options
 */
export interface CreateAccountOptions {
  name?: string;
  source: AccountSource;
  privateKey?: `0x${string}`; // Required for imported accounts
}
